// react-project/app/production/page.tsx
import { Header } from "@/components/header"
import { ProductionOverview } from "@/components/production-overview"
import { ProductionMetrics } from "@/components/production-metrics"
import { ProductionLines } from "@/components/production-lines"
import { ProductionAlerts } from "@/components/production-alerts"

export default function ProductionPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted">
      <Header />
      <main className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-foreground mb-2">생산 현황</h1>
          <p className="text-lg text-muted-foreground">실시간 생산성 모니터링 및 품질 관리</p>
        </div>

        <div className="space-y-6">
          <ProductionOverview />

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2">
              <ProductionLines />
            </div>
            <div className="lg:col-span-1">
              <ProductionAlerts />
            </div>
          </div>

          <ProductionMetrics />
        </div>
      </main>
    </div>
  )
}

// vue-project/src/views/Production.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-background to-muted">
    <Header />

    <main class="container mx-auto px-4 py-8">
      <div class="mb-8">
        <h1 class="text-4xl font-bold text-foreground mb-2">생산 현황</h1>
        <p class="text-lg text-muted-foreground">실시간 생산성 모니터링 및 품질 관리</p>
      </div>

      <div class="space-y-6">
        <ProductionOverview />

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div class="lg:col-span-2">
            <ProductionLines />
          </div>
          <div class="lg:col-span-1">
            <ProductionAlerts />
          </div>
        </div>

        <ProductionMetrics />
      </div>
    </main>
  </div>
</template>

<script setup>
import Header from "@/components/Header.vue"
import ProductionOverview from "@/components/ProductionOverview.vue"
import ProductionMetrics from "@/components/ProductionMetrics.vue"
import ProductionLines from "@/components/ProductionLines.vue"
import ProductionAlerts from "@/components/ProductionAlerts.vue"
</script>
